apiVersion: v2
name: alloy
description: Grafana Alloy - OpenTelemetry collector for logs and metrics
type: application
version: 1.0.0
appVersion: "v1.0.0"

dependencies:
  - name: alloy
    version: 1.4.0
    repository: https://grafana.github.io/helm-charts
