---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCb6WJIYlo7z6aw9CMzBp+6mK9evOPgU9Bvo+JrELlyKmFTm6xeyeO90q4Pr50IDm/uUFQK+u6Vixp20XMAy/ctsxLfjDpcC1qcQZxoF8q2gSSrD9SZfvTXKLttzxWz0aJZun3w66SZGeYXElPgFL5BsD55ahptF4Iv7jnrNRvfv5xf93NreNqAnO1K9Y1ptU3fNoTF8SPBZOF1B+/DAIUdns8wuwV2Iq3ENmx+aU1jyBcQvS/BBlEWrvetV12tD4AsI8GonQOptPQAzL1BSETLXebRnX/dOjoUrhmHcOP3G9YnqtbETYE8RUFlM8oXWb7tPARd3k8XO8e48sHEkPMgfH5wye4mXp94jga/q1HRxzkZC6TtIaFe2r4zrFSgKrVR3jCeJ0VzyAFKPy9Pm4gNcgAwlmbxN8qkBTLZVf4mMqorFX8Gr6r9CcUtRv5+4/zSvzf/Qt9l0o+ukzj7ibCx36pNoodYg6Y9AhG+UJyYg4OZT70JTXDy0Y4Qzzy1zXrv2w256koa+PONkp/LPEoI5p+EJcC660Ib2ueExDoI6AIET+xi8fLYG+bAVld8oGefS3XsjFtRfZS3ZeMRheM3zBKWDJJmahvWAFJLeEziHuX5erVUkyHvalfNqhC760q506GfP+yb5PWJpHm4TGszV6IHYUrYippueAwyg0Ih5XcGUAOF2Bpd6CMsqqiPqv/dDRIijM6dTNIHgrMGwKg=
    JWT_SECRET: AgBS+fuzWEdSw0iSpvYlr91YSqDEhzgv1cZyArAAw/URbyxjp3Jtof088V7fNtG87gYMkVtaYDwRWeXWRqT9AhB+qnvJ5DMn3hcLMmBwjUAPSDNv7nsOJTJ86tZ1T7DNd4qq6kreEyFuFBiK49mKGEPQmFC+v/JyNJ2d9CnZ9Gwl8V0Utds1LuF6GSF4w6ZdslFxpZ2TG1rGG44ZIChJtQgINnlP97CZqPpOc+tOtNJD+aQfQWDPb1a4kgYbI30l7F9L9RDBckVGY7ifqwRwjVZXHWOaHOukBF77B2rnJNBmmvvc7egiejUeS2JxTRK3SrtoRZkWrdjMkx4CUY3iVZSvR+m/XnQXjKLU3Coe6OP7n9cetVFqpLCOzw+9rBq6vSQL+o5gaYQkGoTEFE0tvwkIM6lLghUskRudnWeiDLIiPGuJcvzLA07q8PVkS7Q3QRRTv59RHNjCG+SKjrrEZX1XCX6VeqCNWPzUULi2vGXTjx/hjD/u5RbQrf6g/tHRVKzQPnRZQ3NtxDZSVR3gwP/JAwAeRvf//9SXbo/H8bI7lB6pe0p3MJJ6vBtCZey7zg2CByiDdsB6KWwGqrvDhRnm0G87A7QAiWefLKivgBRKY1j1cN3WM9Xk6CMW/ytArJlD5wTu6qZ6ol2+TrbZPZcF78XzMQJQ91PTwY59UZwjMCbQ8w896W46D6HAZIbpfcVL4VzoWG2IvQ==
  template:
    metadata:
      name: immich-secrets
      namespace: default
    type: Opaque
