apiVersion: v1
kind: Secret
metadata:
  name: power-monitor-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: power-monitor
type: Opaque
stringData:
  ha-token: {{ .Values.homeAssistant.token | quote }}
