{{- if .Values.ssh.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: power-monitor-ssh-key
  namespace: {{ .Release.Namespace }}
  labels:
    app: power-monitor
type: Opaque
stringData:
  id_rsa: {{ .Values.ssh.privateKey | quote }}
{{- end }}
